name: ðŸ§¹ Spotless Check

on:
  push:
    branches:
      - '**'

jobs:
  spotless:
    name: ðŸ§¹ Run Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Decode keystore
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
          cat <<EOF > keystore.properties
          storeFile=release.keystore
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      # ðŸ§© Recreate local.properties from the single secret
      - name: Create local.properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck
